spring:
  application:
    name: CarFusion
  datasource:
    url: jdbc:postgresql://localhost:5432/CarFusion
    username: postgres
    password: ViratKohli18
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
